spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/book?useUnicode=true&amp;characterEncoding=utf-8&amp;autoReconnect=true&amp;zeroDateTimeBehavior=convertToNull&amp;userSSL=true
    username: root
    password: csucoderlee
  jpa:
    hibernate:
      ddl-auto: create
  main:
    show-banner: false
